backend:
  name: github
  repo: SysBioChalmers/sysbio.se
  branch: develop

publish_mode: editorial_workflow
media_folder: "static/img/" # Media files will be stored in the repo under static/img/
public_folder: "img/" # The src attribute for uploaded media will begin with img/

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Martina"]}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "people" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "People" # Used in the UI, ie.: "New Post"
    label_singular: "Person"
    folder: "content/people" # The path to the folder where the documents are stored
    filter: { field: "template", value: "people/profile"}
    create: true # Allow users to create new documents in this collection
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Name and title", name: "name", widget: "string"}
      - {label: "Last name used for sorting", name: "lastname", widget: "string"}
      - {label: "URL, firstname-lastname", name: "title", widget: "string"}
      - {label: "Picture", name: "picture", widget: "image"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Flags", name: "flags", widget: "list", required: false}
      - {label: "Person category", name: "person-category", widget: "select", options: ["A Tenured faculty", "B Non-tenured faculty", "C Affiliated faculty", "D Senior researchers", "E Postdocs", "F PhD students", "G Master students", "H Visiting researchers", "I Guests", "J Research engineers", "K Assistant manager", "L Departamental administration", "M Computational systems biology infrastructure"]}
      - {label: "Template", name: "template", widget: "string", default: "people/profile", pattern: ["people/profile", "Must be 'people/profile'."]}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Other pages"
    files:
      - file: "content/contact.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "select", options: ["Contact"]}
          - {label: "id", name: "id", widget: "select", options: ["contact"]}
          - {label: "Picture", name: "picture", widget: "image"}
          - {label: Body, name: body, widget: markdown}
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "site/content/products/_index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
